version: 1.8.14.{build}
skip_tags: true
max_jobs: 1
configuration: Release
platform: x86
clone_depth: 50
image: Visual Studio 2019
before_build:
- ps: .\update-libraries.ps1
- cmd: nuget restore
build:
  project: Graveyard.sln
  verbosity: minimal
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '$(appveyor_build_version)'
after_build:
  7z a Graveyard.zip "%APPVEYOR_BUILD_FOLDER%\Graveyard\bin\x86\Release\Graveyard.dll" "%APPVEYOR_BUILD_FOLDER%\Graveyard\bin\x86\Release\*-*"
artifacts:
  - path: Graveyard.zip
    name: Graveyard
